PRAGMA foreign_keys=1;

CREATE TABLE DEVICES (
idDevice INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
modelNumber CHAR NOT NULL
);

CREATE TABLE COMMANDS (
idCommand INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
commandName CHARACTER NOT NULL,
commandDescription VARCHAR NULL,
idDevice INTEGER NOT NULL,
FOREIGN KEY (idDevice) REFERENCES DEVICES(idDevice)
);


CREATE TABLE TASKS (
idTask INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
taskName CHARACTER NOT NULL,
idCommand INTEGER NOT NULL,
FOREIGN KEY (idCommand) REFERENCES COMMANDS (idCommand)
);


CREATE TABLE RESPONSES (
idResponse INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
output VARCHAR NOT NULL,
idTask INTEGER NOT NULL,
CONSTRAINT taskFk FOREIGN KEY (idTask) REFERENCES TASKS (idTask)
);
